[workspace]

members = [
    "histo",
    "index_gather",
    "randperm",
    "triangle_count",
    "sparse_matrix_am",
    #"fail_example"
]

[profile.release]
opt-level=3
lto=true
codegen-units=1
debug = false 
panic = "abort"