[workspace]

resolver = "2"

members = [
    "histo",
    "index_gather",
    "randperm",
    "triangle_count",
]

[profile.release]
opt-level=3
lto="fat"
codegen-units=1
debug = true 
panic = "abort"