[package]
name = "randperm"
version = "0.1.0"
authors = ["Ryan D. Friese"]
edition = "2021"

[dependencies]
#serde = { version = "1.0", features = ["derive"] }
#lazy_static = "1.3.0"
rand = "0.6"
lamellar = { version = "0.5.0-rc.1" } #add features = ["enable-rofi"] to use rofi lamellae
#parking_lot = { version = "0.12" }
#tracing = "0.1"
#tracing-futures = "0.2"
#tracing-flame = "0.2"
#tracing-subscriber = "0.3"

[profile.release]
opt-level=3
lto=true
codegen-units=1
debug = true 


[[bin]]
name="randperm"
path="src/randperm.rs"
