[package]
name = "randperm"
version = "0.1.0"
authors = ["Ryan D. Friese"]
edition = "2021"

[dependencies]
#serde = { version = "1.0", features = ["derive"] }
#lazy_static = "1.3.0"
rand = "0.6"
lamellar = { git = "https://github.com/pnnl/lamellar-runtime", tag = "april_2023", features = ["enable-rofi"] }
futures = "0.3.28"
#parking_lot = { version = "0.12" }
#tracing = "0.1"
#tracing-futures = "0.2"
#tracing-flame = "0.2"
#tracing-subscriber = "0.3"


[profile.release]
opt-level=3
lto=true
codegen-units=1
debug = true 

[[bin]]
name="randperm_array_darts"
path="src/randperm_array_darts.rs"


[[bin]]
name="randperm_am_darc_darts"
path="src/randperm_am_darc_darts.rs"

[[bin]]
name="randperm_am_darc_darts_buffered"
path="src/randperm_am_darc_darts_buffered.rs"

[[bin]]
name="randperm_am_array_darts_buffered"
path="src/randperm_am_array_darts_buffered.rs"

[[bin]]
name="randperm_am_darc_push_buffered"
path="src/randperm_am_darc_push_buffered.rs"
