[package]
name = "randperm"
version = "0.1.0"
authors = ["Ryan D. Friese"]
edition = "2021"

[dependencies]
clap = { workspace = true }
futures = { workspace = true }
lamellar = { workspace = true }
rand = { workspace = true }

[features]
ofi = ["lamellar/enable-libfabric"]
ucx = ["lamellar/enable-ucx"]
rofi-c = ["lamellar/enable-rofi-c"]
