[package]
name = "triangle_count"
version = "0.4.1"
authors = ["frie869 <ryan.friese@pnnl.gov>"]
edition = "2021"

[dependencies]
async-std = { workspace = true }
bincode = "1.3"
clap = { workspace = true }
csv = "1"
futures = { workspace = true }
lamellar = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }

[features]
ofi = ["lamellar/enable-libfabric"]
ucx = ["lamellar/enable-ucx"]
rofi-c = ["lamellar/enable-rofi-c"]
