[package]
name = "lamellar_graph"
version = "0.4.1"
authors = ["frie869 <ryan.friese@pnnl.gov>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1"
#lamellar = { git = "https://github.com/pnnl/lamellar-runtime", tag = "april_2023" }   #add features = ["enable-rofi"] to use rofi lamellae
#lamellar = { path = "../../lamellar-runtime-junction", features = ["enable-rofi"] }
lamellar = { git = "https://github.com/pnnl/lamellar-runtime",  branch = "dev", features = ["enable-rofi"]    }   # add features = ["enable-rofi"] to use rofi lamellae
parking_lot = "0.11"
async-std = "1.6.4"
bincode = "1.3"
futures = "0.3"

clap = { version = "4.3.4", features = ["derive", "env"] }

[profile.release]
opt-level=3
lto=true
codegen-units=1
debug = true 


[lib]
name="lamellar_graph"
path="src/lib.rs"

[[bin]]
name="triangle_count"
path="src/triangle_count.rs"

[[bin]]
name="triangle_count_typed_am_group"
path="src/triangle_count_typed_am_group.rs"

[[bin]]
name="triangle_count_buffered"
path="src/triangle_count_buffered.rs"
