[package]
name = "lamellar_graph"
version = "0.4.1"
authors = ["frie869 <ryan.friese@pnnl.gov>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1"
lamellar = { git = "https://github.com/pnnl/lamellar-runtime", branch = "dev" }   #add features = ["enable-rofi"] to use rofi lamellae
parking_lot = "0.11"
async-std = "1.6.4"
bincode = "1.3"

[profile.release]
opt-level=3
lto=true
codegen-units=1
debug = true 


[lib]
name="lamellar_graph"
path="src/lib.rs"

[[bin]]
name="triangle_count"
path="src/triangle_count.rs"

[[bin]]
name="triangle_count_buffered"
path="src/triangle_count_buffered.rs"
